before:
  hooks:
    - go mod download

builds:
  - id: "eru-containerd" 
    main: ./cmd/eru-containerd/main.go
    binary: eru-containerd
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
  - id: "eru-containerd-shim"
    main: ./cmd/eru-systemd-shim/main.go
    binary: containerd-shim-eru-v2
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
